#!/usr/bin/env bash
set -euo pipefail

die(){ echo "[ERROR] $*" >&2; exit 1; }
log(){ echo "[INFO] $*"; }

JOB_DIR="${JOB_DIR:-}"
RUN_PJC_SH="${RUN_PJC_SH:-./run_pjc_patched.sh}"
BASE_PORT="${BASE_PORT:-11001}"
MAX_JOBS="${MAX_JOBS:-4}"
STRICT="${STRICT:-0}"

usage() {
  cat <<EOF
Usage:
  JOB_DIR=runs/<job_id> RUN_PJC_SH=moduleA_psi/scripts/run_pjc.sh $0 [--base-port P] [--max-jobs N]
Requires:
  - <job_dir>/job_shard_meta.json generated by shard_pjc_inputs.py
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-port) BASE_PORT="$2"; shift 2 ;;
    --max-jobs) MAX_JOBS="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown arg: $1" ;;
  esac
done

[[ -n "$JOB_DIR" ]] || die "JOB_DIR required"
JOB_DIR="$(cd "$JOB_DIR" && pwd)"
[[ -f "$JOB_DIR/job_shard_meta.json" ]] || die "missing $JOB_DIR/job_shard_meta.json"

run_one() {
  local subdir="$1"
  local port="$2"
  export OUT_DIR="$subdir"
  export SERVER_CSV="$subdir/server.csv"
  export CLIENT_CSV="$subdir/client.csv"
  export SERVER_ADDR="127.0.0.1:$port"
  export JOB_ID="$(basename "$JOB_DIR")"
  bash "$RUN_PJC_SH"
}

PY_LIST='import json,sys; m=json.load(open(sys.argv[1])); 
targets=m.get("targets",[]);
for t in targets:
  base=t["dir"]
  bucket=t.get("bucket")
  for s in t.get("shards",[]):
    print((bucket if bucket is not None else "__ROOT__") + "\t" + s["dir"] + "\t" + str(s.get("exposure_n", 0)) + "\t" + str(s.get("purchase_n", 0)))'

mapfile -t ITEMS < <(python3 -c "$PY_LIST" "$JOB_DIR/job_shard_meta.json")

pids=()
count=0
idx=0
for item in "${ITEMS[@]}"; do
  IFS=$'\t' read -r bucket subdir exposure_n purchase_n <<<"$item"
  port=$((BASE_PORT + idx))
  if [[ "${exposure_n:-0}" == "0" || "${purchase_n:-0}" == "0" ]]; then
    log "skip empty shard: bucket=$bucket dir=$subdir exposure_n=${exposure_n:-0} purchase_n=${purchase_n:-0}"
    mkdir -p "$subdir"
    cat > "$subdir/attribution_result.json" <<JSON
{
  "job_id": "$(basename "$JOB_DIR")",
  "server_addr": "skipped-empty-shard",
  "intersection_size": 0,
  "intersection_sum": 0
}
JSON
    idx=$((idx+1))
    continue
  fi
  log "run shard: bucket=$bucket dir=$subdir port=$port"
  run_one "$subdir" "$port" &
  pids+=($!)
  count=$((count+1))
  idx=$((idx+1))
  if [[ "$count" -ge "$MAX_JOBS" ]]; then
    wait -n
    count=$((count-1))
  fi
done
wait

# merge per target (sum shard outputs)
MERGE_PY='
import json, os, sys
job_dir = sys.argv[1]
meta = json.load(open(os.path.join(job_dir, "job_shard_meta.json")))
for t in meta.get("targets", []):
    total_size = 0
    total_sum = 0
    shards = []
    for s in t.get("shards", []):
        path = os.path.join(s["dir"], "attribution_result.json")
        if not os.path.isfile(path):
            continue
        r = json.load(open(path))
        total_size += int(r.get("intersection_size", 0))
        total_sum += int(r.get("intersection_sum", 0))
        shards.append({"shard_id": s["shard_id"], "intersection_size": int(r.get("intersection_size",0)), "intersection_sum": int(r.get("intersection_sum",0))})
    out = {"intersection_size": total_size, "intersection_sum": total_sum, "shards": shards}
    out_dir = t["dir"]
    with open(os.path.join(out_dir, "attribution_result.json"), "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

# merge to job level if multiple business buckets exist
job_meta = json.load(open(os.path.join(job_dir, "job_meta.json")))
bucket = job_meta.get("bucket", {}) or {}
bucket_field = bucket.get("field")
outputs = bucket.get("outputs") or []
if bucket_field and outputs:
    total_size = 0
    total_sum = 0
    rows = []
    for o in outputs:
        b = o.get("bucket")
        sub = os.path.join(job_dir, f"bucket_{bucket_field}={b}", "attribution_result.json")
        if not os.path.isfile(sub):
            continue
        r = json.load(open(sub))
        total_size += int(r.get("intersection_size",0))
        total_sum += int(r.get("intersection_sum",0))
        rows.append({"bucket": b, "intersection_size": int(r.get("intersection_size",0)), "intersection_sum": int(r.get("intersection_sum",0))})
    with open(os.path.join(job_dir, "attribution_result.json"), "w", encoding="utf-8") as f:
        json.dump({"bucket_field": bucket_field, "intersection_size": total_size, "intersection_sum": total_sum, "buckets": rows}, f, ensure_ascii=False, indent=2)
'
python3 -c "$MERGE_PY" "$JOB_DIR"

log "done: merged shard results under $JOB_DIR"
