apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: seccomp-tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    version: 1
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: ""
      serviceMap:
        datasourceUid: ""

  - name: Prometheus
    type: prometheus
    uid: seccomp-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 15s
