agent {
  data_dir                  = "/run/spire/agent/data"
  log_level                 = "INFO"
  server_address            = "spire-server.spire.svc.cluster.local"
  server_port               = "8081"
  socket_path               = "/run/spire/agent/sockets/spire-agent.sock"
  trust_bundle_path         = "/run/spire/agent/bundle/bundle.crt"
  trust_domain              = "example.org"
}

plugins {
  NodeAttestor "k8s_sat" {
    plugin_data {
      cluster = "pjc-cluster"
    }
  }
  KeyManager "memory" {
    plugin_data {}
  }
  WorkloadAttestor "k8s" {
    plugin_data {
      kubelet_read_only_port      = 10255
      skip_kubelet_verification   = false
      node_name_env               = "MY_NODE_NAME"
    }
  }
  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
